# Generated by Django 3.1.2 on 2020-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_auto_20201123_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='registration',
            field=models.CharField(help_text='recommended height 1000', max_length=1000),
        ),
    ]
