# Generated by Django 3.1.2 on 2020-11-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daythree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('imageOne', models.ImageField(blank=True, upload_to='images')),
                ('imageTwo', models.ImageField(blank=True, upload_to='images')),
                ('imageThree', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
                ('eventhead', models.CharField(max_length=1000)),
                ('rules', models.TextField(blank=True)),
                ('registrationform', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MainDayThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(blank=True, upload_to='images')),
                ('imageTwo', models.ImageField(blank=True, upload_to='images')),
                ('imageThree', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
                ('day', models.ManyToManyField(blank=True, related_name='dayofdaythree', to='maineventsdaythree.Daythree')),
            ],
        ),
        migrations.AddField(
            model_name='daythree',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='eventsofday', to='maineventsdaythree.Event'),
        ),
    ]
